### ISSUE TITLE
AsyncTask is deprecated, any plans to move to Coroutines?

### ISSUE THREAD

**Issue by soulgen** [danjdt/android-pdfviewer#7]

**Comment by Sash0k** [comment]
I tried switching to coroutines in #10, but reverting it back (if you interesting, see commit history for details).

Problem, that we can’t ever have two pages open at the same time. If we simply offload the rendering work to a thread pool (e.g. Dispatchers.IO), we run the risk of trying to open a page in one thread while a different thread is still rendering another one, causing `java.lang.IllegalStateException: Current page not closed`, as explained in [that arcticle](https://medium.com/@aditya09tyagi/android-pdf-reader-using-pdfrenderer-6daa2dacec1a).

Android 12 still have AsyncTask support, so i decided to continue using autor's implementation

**Comment by soulgen** [comment]
You could use Executors.newSingleThreadExecutor().asCoroutineDispatcher() to avoid IllegalStateException

**Comment by Sash0k** [comment]
в 2022 старый добрый асинктаск всё ещё в строю (посмотрел в тирамису - работает)

затаскивать корутины ради корутин - только раздувать приложение
если будет время, запилю нормальный ридер на базе этой либы
